name: photo_stock
description: Входное задание Surf.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  get_it: ^7.2.0
  json_annotation: ^4.7.0
  cached_network_image: ^3.2.2
  google_fonts: ^3.0.1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true